### ISSUE TITLE
installation stuffs

### ISSUE THREAD

**Issue by Cherkah** [lzap/dunst-checkmail#1]
hi and thank for your job...

1) i would like to know how to proceed the instalation ?

2) can i change dunst for my default notification deamon (libnotify)? which file should i change?

**Comment by Cherkah** [comment]
hi
ok for th installation: compilation (got some errors...). 
now i'm working on change the code to deal with my default notification deamon.

**Comment by lzap** [comment]
Sure send patches, it is very dirty thing and I actually stop using it, I have written similar thing bug in Go :-)

https://github.com/lzap/gocheckmail
